# Generated by Django 4.2.5 on 2024-08-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("event_time", models.TimeField(blank=True, null=True)),
                ("details", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
