# Generated by Django 4.2.5 on 2024-08-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField()),
                ("details", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.EmailField(max_length=254)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedl.event"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "email_id")},
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Meeting",
        ),
        migrations.AddField(
            model_name="event",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schedl.user"
            ),
        ),
    ]
